### ISSUE TITLE
Add descriptions for settings

### ISSUE THREAD

**Issue by magicznyleszek** [subesokun/atom-tree-view-git-status#14]
I don't know what `Auto Toggle` does. I tried switching on/of, clicking/hovering stuff and changing branches via command line git, but I don't see any difference.

**Comment by subesokun** [comment]
Hi @smutnyleszek! Thanks, that's a good hint and I'll add some proper description to each setting in case it's not self-explaining.

Regarding the `Auto Toggle` feature, if enabled the `tree-view-git-status` packages gets automatically enabled i.e. toggled when starting the Atom editor. Some person might wish that by default this package isn't enabled when starting Atom so that they can manually toggle it if needed while the Atom is running. "Disabled" means that you'll see no Git status information like the branch name that gets added by this package in the tree view (just the plain tree view).

Hope that makes it a bit clearer for you what this setting is good for.

**Comment by subesokun** [comment]
Fixed via PR #27
