### ISSUE TITLE
Integrate tooltip into project root node

### ISSUE THREAD

**Issue by AddictArts** [subesokun/atom-tree-view-git-status#15]
Is there a debug mode or a way to determine why the blue Head, Origin, and Path do not appear either as a tooltip if that is what it should do, or other. Thanks for the help.

**Comment by subesokun** [comment]
Hi @AddictArts, actually that's a bug that I also noticed recently. With Ubuntu it worked so far fine for me but on Windows it's not showing at all. It's on my todo list and I'll try to have this weekend a look on it.

But if you also want to debug it feel free to do so :) The issue is around [this line](https://github.com/subesokun/atom-tree-view-git-status/blob/4a402200ee453636871cf00cb67d8c6100bf2360/lib/tooltip.coffee#L65) as for some reason the tooltip get immediately destroyed before after the mouseEnter event occurred and hence the tooltip is not appearing.

**Comment by midwire** [comment]
I'm also not seeing any tooltip on OSX. I've not tried to dig into it but it seems to just not be working at all.

**Comment by subesokun** [comment]
Hi @midwire, yes sadly there have been some breaking changes in Atom and since then the tooltip feature is not working anymore :( There has been a discussion regarding a native Popup API in Atom to display such tooltips but it got stuck somewhere half way, [see here](https://discuss.atom.io/t/create-an-overlay-panel-container-layer/16006). Hopefully I'll find some time in the next weeks to finally fix this issue.

**Comment by midwire** [comment]
Ah, that is unfortunate :( I was looking forward to this plugin. Thanks for your hard work on it anyway. I'm sure it will be great once the Atom team can stabilize the API.

**Comment by subesokun** [comment]
As it's still not clear how to create such tooltips in Atom I'll remove this feature for now and re-add it once there is some default tooltip generator.

**Comment by subesokun** [comment]
This project is no longer maintained as Atom and all repositories under Atom will be archived on December 15, 2022. Learn more in the [official announcement](https://github.blog/2022-06-08-sunsetting-atom/). Thank you for your interest in this project and your support!
