### ISSUE TITLE
Does not show changed files in Atom 1.5.1

### ISSUE THREAD

**Issue by tsabolov** [subesokun/atom-tree-view-git-status#21]
After upgrading Atom to 1.5.1 the behaviour of the plugin changed:

Steps to reproduce the problem:
1. Add git-powered project folder to tree-view
2. Change some file. In tree view there will appear a yellow dot near changed file name.
3. Switch away from Atom (i.e. to browser to see the change), and then switch back to Atom. All files in tree view are displayed as non-changed.

The issue first appeared in 1.5.0-beta. Now I checked it against 1.5.1, 1.5.2 and 1.6.0-beta — it remains.
It's Mac version btw.

**Comment by subesokun** [comment]
@tsabolov, thanks for reporting this issue! I'll try to investigate this issue as soon as I can.

**Comment by subesokun** [comment]
@tsabolov I was testing now the tree-view-git-status package against v1.5.x and v1.6.x but so far all test have been passing. You've mentioned that all files in the tree vie are displayed as non-changed or? Actually what this package does is just to color the root folder of that project but not the files itself. Hence the behavior you're observing might be caused by a bug in the Atom [git-utils](https://github.com/atom/git-utils) itself. You might need to report your issue there as I can't help you with that :(

**Comment by tsabolov** [comment]
@subesokun Now I see that your package is not the root of the problem (opened DevTools and found out that styling of individual changed files comes from a file `/Users/##/.atom/packages/native-ui/index.less`) Anyway thank you for showing me the right direction and sorry for disturbing
`¯\_(ツ)_/¯`
