### ISSUE TITLE
show branch info for subfolders

### ISSUE THREAD

**Issue by valdrinkoshi** [subesokun/atom-tree-view-git-status#35]
It would be nice to see the branch information for each subfolder:
<img width="191" alt="screen shot 2016-08-25 at 10 40 36 am" src="https://cloud.githubusercontent.com/assets/6173664/17979713/e87b2be0-6ab0-11e6-9d50-5e1727660674.png">

**Comment by subesokun** [comment]
Hi @valdrinkoshi, this feature would be only possible if Atom recognizes the sub folders as repositories. But as shown on your image Atom currently doesn't detect if those sub folders are repositories. Maybe you can file an issue directly on Atom so that they implement this feature. Hence I'm closing this issue for now but feel free to ping me here again once this feature is available in Atom :)
