### ISSUE TITLE
Nothing is appearing?

### ISSUE THREAD

**Issue by mikeerickson** [subesokun/atom-tree-view-git-status#43]
I have the plugin installed and configured, but nothing is displaying?

![image](https://cloud.githubusercontent.com/assets/183153/21573167/2e677bce-ce96-11e6-833a-33408890374c.png)

![image](https://cloud.githubusercontent.com/assets/183153/21573171/39291734-ce96-11e6-8a55-5492bf26f837.png)

**Comment by mikeerickson** [comment]
I have this same plugin installed on work machine and all is groovy there? Am I missing something here?

**Comment by mikeerickson** [comment]
Here is another project (so it is not associated to the above project specifically) 

![image](https://cloud.githubusercontent.com/assets/183153/21573196/8672ba36-ce96-11e6-90ee-7212725356ef.png)

**Comment by mikeerickson** [comment]
Theme:  Seti Classic (this is the same theme I use at work and no issues)

![image](https://cloud.githubusercontent.com/assets/183153/21573212/afb2cb66-ce96-11e6-81e7-0133a2da9bcc.png)

**Comment by userlerueda** [comment]
@mikeerickson I had the same problem, but mine was that the top level project directory I added was not the top level directory for the git repository, I found out they both had to match for anything to be highlighted, is this your case?

**Comment by mikeerickson** [comment]
@userlerueda So far as I can tell, they are both at the "top level" (which is my project root).

**Comment by mikeerickson** [comment]
@userlerueda Here is what is bizarre

1. project is tree does not have current branch
2. using the [git-status](https://atom.io/packages/git-status) package, it correctly shows branch (see bottom right)

![image](https://cloud.githubusercontent.com/assets/183153/22004578/97403522-dc11-11e6-8b7a-16fdf9a5c7fe.png)

**Comment by subesokun** [comment]
Sorry for the late answer! I'll try to analyze this issue by this weekend.

**Comment by subesokun** [comment]
Hi @mikeerickson, I've installed now Seti-Classic theme + syntax as well and the git status gets correctly displayed in my case. Hence the theme itself seems to be compatible with the tree-view-git-status package.

@userlerueda Regarding the top level directory issue, this has been already solved in some previous release so you can add the top level directory or any other sub directory of the project and the git status should be still displayed :)

The reason why the [git-status](https://atom.io/packages/git-status) package is able to show the git status is most likely because it doesn't rely on Atom's API to retrieve the git status information, instead it uses the git client of the host system directly to retrieve these information.

So it sound to me that for some reason Atom is not able to recognize your project as a git project. If you open your project and open a file of it which is under version control do you see in the bottom right corner of Atom the git branch icon + branch name?

Btw. is this top level `Pane` folder in your tree view provided by some package? It doesn't look like a standard project folder. Not sure if this one doesn't play so well together with the tree-view-git-status package.

**Comment by userlerueda** [comment]
Hi @subesokun I guess I didn´t explain myself correctly, what I meant is say I have a parent folder called GitHub, I place all my repositories inside as folders, I wish to be able to add the GitHub main folder and have the option to see the individual folders (repositories) and once I clic on them for them to show me which branch is being used, etc. Not sure if it makes sense, maybe it doesn't.

**Comment by subesokun** [comment]
I see, yes indeed Atom is not indented to use that way. Atom won't recognize a folder as a Git repository if the current project folder is not the root Git folder itself (or any subfolder of it). Instead of your GitHub folder you should add each repository folder separately as a project to Atom. If you've troubles to add all repos to your Atom upon a restart you can also use the [project-manager](https://atom.io/packages/project-manager) package to store and restore them. 

Closing this issue for now but feel free to comment :)
