### ISSUE TITLE
Files not colored

### ISSUE THREAD

**Issue by Chaoste** [subesokun/atom-tree-view-git-status#52]
Hello erveryone,

I just installed "atom-tree-view-git-status" without having any other packages than the core packages. In some other devices I already saw files being colored by their git status (orange, green or gray), but this is not happening right now for a new opened project ("File->Add Project Folder").

Maybe this isn't a bug but just my misunderstanding which causes the problem. The folder is actually visualized like a normal folder and not like a project.

Thanks in advance,
Thomas

---

Package Version: 1.4.0

OS: Windows 10
Atom Version: 1.14.2 (latest right now)
Atom UI Theme: One Dark
Atom Syntax Theme: One Dark

**Comment by 747** [comment]
Same here. In my environment only project folders are colored. I'd like to know what I'm missing.

OS: Windows 10 (Creators Update)
Atom: v1.17.2 ia32

**Comment by subesokun** [comment]
Hi @Chaoste, actually this isn't an issue of the tree-view-git-status package but of the tree-view core package of Atom itself. What this tree-view-git-status package does is actually only to color the project root folder but not the files within it. You may report your issue here https://github.com/atom/tree-view
